"use client";

import { I18n } from "@/providers/i18n";

import { Inter } from "next/font/google";
import "./globals.scss";

import Footer from "@/components/footer";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

const RootLayout = ({ children }) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<I18n>
					<Header />
					<main>
						{children}
					</main>
					<Footer />
				</I18n>
			</body>
		</html>
	);
};

export default RootLayout;
